env: Acrobot-v1
num_episodes: 10000
num_play_episodes: 10

model: DNN
model_options:
  layers: [24, 12]
  activations: ['relu', 'relu', 'softmax']
  learning_rate: 0.01  # learning rate in deep learning

algo: Q_LEARN_BATCH
algo_options:
  gamma: 0.99 #['range', 0.5, 1.0, 0.1]  # decay rate of past observations
  alpha: 1e-4 #0.7 #['range', 0.5, 1.0, 0.1]  # learning rate in the Q value
  eps: 1.0
  eps_decay_factor: 0.9995
